likelion_11th/accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"
urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('signup/', signup, name="signup"),
]

likelion_11th/likelion_11th/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likelion_11th/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', mainpage, name="mainpage"),
    path('second/', secondpage, name='secondpage'),
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('<int:id>', detail, name="detail"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('tag/', tag_list, name="tag_list"),
    path("tag/<int:tag_id>", tag_blogs, name="tag_blogs"),
]

likelion_11th/users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('mypage/', mypage, name="mypage"),
]

likelion_11th/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.TextField(max_length=10)
    department = models.TextField(null=True, max_length=30)

likelion_11th/main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, blank=False)

    def __str__(self) :
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=200)
    writer = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to="blog/", blank=True, null=True)
    tags = models.ManyToManyField(Tag, related_name='blogs', blank=True)

    def __str__(self):
        return self.title
    
    def summary(self):
        return self.body[:20]
    
class Comment(models.Model):
    content = models.TextField()
    pub_date = models.DateTimeField()
    writer = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, null=False, blank=False, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, related_name='comments', blank=True)

    def __str__(self):
        return self.blog.title + " : " + self.content[:20]

likelion_11th/users/models.py
from django.db import models

# Create your models here.

likelion_11th/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.models import User
from .models import Profile

# Create your views here.

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(request, username = username, password = password)

        if user is not None:
            auth.login(request, user)
            return redirect('main:mainpage')
        else:
            return render(request, 'accounts/login.html')
        
    elif request.method == 'GET':
        return render(request, 'accounts/login.html')
    
def logout(request):
    auth.logout(request)
    return redirect('main:mainpage')

def signup(request):
    if request.method == 'POST':

        if request.POST['password'] == request.POST['confirm']:
            user = User.objects.create_user(
                username=request.POST['username'],
                password=request.POST['password']
            )
            nickname = request.POST['nickname']
            department = request.POST['department']

            profile = Profile(user=user, nickname=nickname, department=department)
            profile.save()

            auth.login(request, user)
            return redirect('/')
    return render(request, 'accounts/signup.html')

likelion_11th/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Blog, Comment, Tag
from django.utils import timezone

# Create your views here.

def mainpage(request):
    blogs = Blog.objects.all()  # 해당 객체의 모든 내용을 담겠다 -> Blog에 있는 모든 내용들을 담는다는 뜻
    return render(request, 'main/mainpage.html', {'blogs':blogs})

def secondpage(request):
    return render(request, 'main/secondpage.html')

def new(request):
    return render(request, 'main/new.html')

def detail(request, id):
    blog = get_object_or_404(Blog, pk = id)
    if request.method == 'GET':
        comments = Comment.objects.filter(blog=blog)
        return render(request, 'main/detail.html',  {
            'blog' :blog,
            'comments' : comments,
        })
    elif request.method == "POST":
        new_comment = Comment()
        new_comment.blog = blog
        new_comment.writer = request.user
        new_comment.content = request.POST['content']
        new_comment.pub_date = timezone.now()
        
        new_comment.save()

        tag_list = [w[1:] for w in new_comment.content.split() if w.startswith('#')]

        for t in tag_list:
            tag, _ = Tag.objects.get_or_create(name=t)
            new_comment.tags.add(tag)
        return redirect('main:detail', id)

def create(request):
    if request.user.is_authenticated:
        new_blog = Blog()
        new_blog.title = request.POST['title']
        new_blog.writer = request.user
        new_blog.pub_date = timezone.now()
        new_blog.body = request.POST['body']
        new_blog.image = request.FILES.get('image')

        new_blog.save()

        tag_list = [w[1:] for w in new_blog.body.split() if w.startswith('#')]
        
        for t in tag_list:
            tag, _ = Tag.objects.get_or_create(name=t)
            new_blog.tags.add(tag)
        return redirect('main:detail', new_blog.id)
    else :
        return redirect('accounts:login')

def edit(request, id):
    edit_blog = Blog.objects.get(id = id)
    return render(request, 'main/edit.html', {'blog' : edit_blog})

def update(request, id):
    if request.user.is_authenticated:
        update_blog = Blog.objects.get(id = id)
        update_blog.title = request.POST['title']
        update_blog.pub_date = timezone.now()
        update_blog.body = request.POST['body']

        update_blog.save()

        update_blog.tags.clear()
        tag_list = [w[1:] for w in update_blog.body.split() if w.startswith('#')]

        for t in tag_list:
            tag, _ = Tag.objects.get_or_create(name=t)
            update_blog.tags.add(tag)

        return redirect('main:detail', update_blog.id)
    return redirect('accounts:login')

def delete(request, id):
    delete_blog = Blog.objects.get(id = id)
    delete_blog.delete()
    return redirect('main:mainpage')

def tag_list(request):
    tags =  Tag.objects.all()
    return render(request, 'main/tag_list.html', {
        'tags' : tags,
    })

def tag_blogs(request, tag_id):
    tag = get_object_or_404(Tag, id = tag_id)
    blogs_with_content_tags = Blog.objects.filter(tags=tag)
    blogs_with_comment_tags = Blog.objects.filter(comment__tags=tag)

    blogs = blogs_with_content_tags.union(blogs_with_comment_tags)
    return render(request, 'main/tag_blogs.html', {
        'tag' :tag,
        'blogs' : blogs,
    })

likelion_11th/users/views.py
from django.shortcuts import render

# Create your views here.
def mypage(request):
    return render(request, "users/mypage.html")

likelion_11th/accounts/templates/accounts/login.html
{% extends 'base.html' %} {% load static %} {% block content %}

<form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %} id : <input type="text" name="username" /><br />
    password : <input type="password" name="password" /><br />
    <input type="submit" value="로그인" />
</form>

{% endblock %}

likelion_11th/accounts/templates/accounts/signup.html
{% extends 'base.html' %} {% load static %} {% block content %}

<form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    <p>username</p>
    <input type="text" name="username" />
    <br />

    <p>password</p>
    <input type="password" name="password" />
    <br />

    <p>confirm</p>
    <input type="password" name="confirm" />
    <br />

    <p>별명</p>
    <input type="text" name="nickname" />
    <br />

    <p>학과</p>
    <input type="text" name="department" />
    <br />

    <input type="submit" value="회원가입" />
</form>

{% endblock %}

likelion_11th/likelion_11th/templates/base.html
<!doctype html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/project.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>dgu_likelion11th</title>
</head>
<body>
  {% include 'shared/_navbar.html' %}
  {% block content %}

  {% endblock %}
</body>
</html>

likelion_11th/likelion_11th/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid" style="background-color: #e3f2fd">
        <!-- mainpage 링크 연결 -->
        <a class="navbar-brand" href="{% url 'main:mainpage' %}"
            >DGU_likelion_11th</a
        >
        <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <!-- secondpage 링크 연결 -->
                    <a
                        class="nav-link active"
                        aria-current="page"
                        href="{% url 'main:secondpage' %}"
                        >Secondpage</a
                    >
                    <a
                        class="nav-link active"
                        aria-current="page"
                        href="{% url 'main:tag_list' %}"
                        >태그 게시물 보기</a
                    >
                </li>

                <li class="nav-item dropdown">
                    {% if user.is_authenticated %}
                    <!--로그인시 보이는 화면-->
                    <a
                        class="nav-link dropdown-toggle"
                        href="#"
                        id="navbarDropdown"
                        role="button"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                    >
                        {{user.username}}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a
                                class="dropdown-item"
                                href="{% url 'accounts:logout' %}"
                                >로그아웃</a
                            >
                        </li>
                        <li>
                            <a
                                class="dropdown-item"
                                href="{% url 'users:mypage' %}"
                                >mypage</a
                            >
                        </li>
                    </ul>

                    {% else %}

                    <!--로그아웃시 보이는 화면-->
                    <a
                        class="nav-link dropdown-toggle"
                        href="#"
                        id="navbarDropdown"
                        role="button"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                    >
                        LOGIN
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a
                                class="dropdown-item"
                                href="{% url 'accounts:login' %}"
                                >login</a
                            >
                        </li>
                        <li>
                            <a
                                class="dropdown-item"
                                href="{% url 'accounts:signup' %}"
                                >signup</a
                            >
                        </li>
                    </ul>

                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

likelion_11th/main/templates/main/detail.html
{% extends 'base.html' %} {% load static %} {% block content %}

<h1>{{blog.title}}</h1>
작성자 : {{blog.writer}} 날짜 : {{blog.pub_date}}
<hr />
{% if blog.image %}
<p><img src="{{blog.image.url}}" alt="사진" /></p>
{% endif %}
<p>{{blog.body}}</p>

<p>
    태그 : {% for tag in blog.tags.all %}
    <a href="{% url 'main:tag_blogs' tag.pk %}">{{ tag.name }}</a> {% endfor %}
</p>

{% if blog.writer == user %}
<a href="{% url 'main:edit' blog.id %}">수정하기</a>
<a href="{% url 'main:delete' blog.id %}">삭제하기</a>
{% endif %}

<div class="comment_container">
    <div class="comment_form">
        <h2>댓글 작성하기</h2>
        <form method="POST" action="{% url 'main:detail' blog.id %}">
            {% csrf_token %}
            <input type="text" name="content" />
            <input type="submit" name="submit" />
        </form>
    </div>
    <div class="comment_list">
        {% for c in comments %}
        <hr />
        <h4>작성자 : {{c.writer}}</h4>
        <p>내용 : {{c.content}}</p>
        <p>
            태그 : {% for tag in c.tags.all %}
            <a href="{% url 'main:tag_blogs' tag.pk %}">{{ tag.name }}</a> {% endfor %}
        </p>
        <p>{{c.pub_date}}</p>
        {% endfor %}
    </div>
</div>

{% endblock %}

likelion_11th/main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>글 수정하기</h1>
    <form action="{% url 'main:update' blog.id %}" method="POST">
        {%csrf_token%}
        <p>제목 : <input type="text" name="title" value="{{blog.title}}"></p>
        <p>작성자 : <input type="text" name="writer" value="{{blog.writer}}"></p>
        <p>내용 : <textarea name="body" id="" cols="30" rows="10" >{{blog.body}}</textarea></p>
        <button type="submit">제출</button>
    </form>
</div>
{% endblock %}

likelion_11th/main/templates/main/mainpage.html
{% extends 'base.html' %} {% load static %} {% block content %}

<h1>Hello! _mainpage</h1>
<img src="{% static 'images/logo.jpg' %}" style="width: 500px" />
<br />
{% if user.is_authenticated %}
<a href="{%url 'main:new' %}">글쓰기</a>
{% endif %}

<h1>글 목록</h1>

<div>
    {% for blog in blogs %}
    <div>
        <h3>{{blog.title}}</h3>
        {{blog.writer}}<br />
        {{blog.summary}}
        <a href="{% url 'main:detail' blog.id %}">...자세히</a>
        <br />
    </div>
    {% endfor %}
</div>

{% endblock %}

likelion_11th/main/templates/main/new.html
{% extends 'base.html' %} {% load static %} {% block content %}

<form
    action="{%url 'main:create'%}"
    method="POST"
    enctype="multipart/form-data"
>
    {%csrf_token%}
    <p>제목 : <input type="text" name="title" /></p>
    <!-- <p>작성자 : <input type="text" name="writer" /></p> -->
    <p>사진 : <input type="file" name="image" /></p>
    <p>
        내용 :
        <textarea type="text" name="body" id="" cols="30" rows="10"></textarea>
    </p>
    <button type="submit">제출</button>
</form>

{% endblock %}

likelion_11th/main/templates/main/secondpage.html
{% extends 'base.html' %}
{% block content %}

<p>Hello! _secondpage</p>

{% endblock %}

likelion_11th/main/templates/main/tag_blogs.html
{% extends 'base.html' %} {% block content %}

<div class="blog_container">
    <h1>#{{tag}} 게시물 목록</h1>
    <hr />
    {% for b in blogs %}
    <div class="blog">
        <h2 class="title">
            <a href="{% url 'main:detail' b.id %}">제목 : {{ b.title }}</a>
        </h2>
        <h4>작성자 : {{ b.writer }}</h4>
        <p>내용 : {{ b.body }}</p>
    </div>
    <hr />
    {% endfor %}
</div>

{% endblock %}

likelion_11th/main/templates/main/tag_list.html
{% extends 'base.html' %} {% block content %}

<div class="tag_container">
    <h1>해시태그 목록</h1>
    <hr />
    {% for t in tags %}
    <div class="tag">
        <h2 class="title">
            <a href="{% url 'main:tag_blogs' t.id %}">#{{t.name}}</a>
        </h2>
    </div>
    <hr />
    {% endfor %}
</div>

{% endblock %}

likelion_11th/users/templates/users/mypage.html
{% extends 'base.html' %} {% load static %} {% block content %}

<h1>내 이름은 뭘까용.</h1>

<h3>아이디 : {{ user.username }}</h3>
<h3>{{ user.profile.nickname }}님 안녕하세요.</h3>
<h3>당신의 학과는 {{ user.profile.department }} 입니다.</h3>

{% endblock %}